-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-08-29 09:42:39 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g


CREATE TABLE t_compra (
    cd_compra                     NUMBER NOT NULL,
    t_fornecedor_cd_fornecedor    NUMBER NOT NULL,
    t_forma_pagto_cd_tipo_pagto   NUMBER NOT NULL,
    t_tempo_sk_tempo              NUMBER NOT NULL,
    t_hospital_cd_hospital        NUMBER NOT NULL,
    t_produto_cd_produto          NUMBER NOT NULL,
    vl_total                      NUMBER NOT NULL,
    vl_desconto                   NUMBER NOT NULL,
    vl_preco                      NUMBER NOT NULL,
    vl_pct_desconto               NUMBER NOT NULL,
    vl_imposto_pago               NUMBER NOT NULL,
    vl_pct_imposto_pago           NUMBER NOT NULL
);

ALTER TABLE t_compra
    ADD CONSTRAINT t_compra_pk PRIMARY KEY ( cd_compra,
                                             t_tempo_sk_tempo,
                                             t_fornecedor_cd_fornecedor,
                                             t_forma_pagto_cd_tipo_pagto,
                                             t_hospital_cd_hospital,
                                             t_produto_cd_produto );

CREATE TABLE t_forma_pagto (
    cd_tipo_pagto   NUMBER NOT NULL,
    ds_pagto        VARCHAR2(20) NOT NULL,
    qt_parcelas     NUMBER NOT NULL
);

ALTER TABLE t_forma_pagto ADD CONSTRAINT t_forma_pagto_pk PRIMARY KEY ( cd_tipo_pagto );

CREATE TABLE t_fornecedor (
    cd_fornecedor   NUMBER NOT NULL,
    nr_cnpj         NUMBER NOT NULL,
    nm_fornecedor   VARCHAR2(20) NOT NULL,
    dt_fundacao     DATE NOT NULL,
    nr_estrelas     NUMBER NOT NULL,
    nm_estado       VARCHAR2(20) NOT NULL,
    nm_cidade       VARCHAR2(20) NOT NULL,
    nm_bairro       VARCHAR2(20) NOT NULL
);

ALTER TABLE t_fornecedor ADD CONSTRAINT t_fornecedor_pk PRIMARY KEY ( cd_fornecedor );

CREATE TABLE t_hospital (
    cd_hospital    NUMBER NOT NULL,
    nm_hospital    VARCHAR2(20) NOT NULL,
    nm_estado      VARCHAR2(20) NOT NULL,
    nm_cidade      VARCHAR2(20) NOT NULL,
    nm_bairro      VARCHAR2(20) NOT NULL,
    qt_adquirida   NUMBER NOT NULL
);

ALTER TABLE t_hospital ADD CONSTRAINT t_hospital_pk PRIMARY KEY ( cd_hospital );

CREATE TABLE t_produto (
    cd_produto          NUMBER NOT NULL,
    cd_barras           NUMBER NOT NULL,
    ds_tipo_embalagem   VARCHAR2(20) NOT NULL,
    nm_produto          VARCHAR2(20) NOT NULL
);

ALTER TABLE t_produto ADD CONSTRAINT t_produto_pk PRIMARY KEY ( cd_produto );

CREATE TABLE t_tempo (
    sk_tempo          NUMBER NOT NULL,
    dt_tempo          DATE NOT NULL,
    dt_ano            DATE NOT NULL,
    dt_mes            DATE NOT NULL,
    dt_dia            NUMBER NOT NULL,
    dt_hora           DATE NOT NULL,
    qt_dias_entrega   NUMBER NOT NULL
);

ALTER TABLE t_tempo ADD CONSTRAINT t_tempo_pk PRIMARY KEY ( sk_tempo );

ALTER TABLE t_compra
    ADD CONSTRAINT fk_t_compra_t_hospital FOREIGN KEY ( t_hospital_cd_hospital )
        REFERENCES t_hospital ( cd_hospital );

ALTER TABLE t_compra
    ADD CONSTRAINT fk_t_compra_t_produto FOREIGN KEY ( t_produto_cd_produto )
        REFERENCES t_produto ( cd_produto );

ALTER TABLE t_compra
    ADD CONSTRAINT fk_t_compra_t_tempo FOREIGN KEY ( t_tempo_sk_tempo )
        REFERENCES t_tempo ( sk_tempo );

ALTER TABLE t_compra
    ADD CONSTRAINT fk_t_forma_pagto FOREIGN KEY ( t_forma_pagto_cd_tipo_pagto )
        REFERENCES t_forma_pagto ( cd_tipo_pagto );

ALTER TABLE t_compra
    ADD CONSTRAINT fk_t_fornecedor FOREIGN KEY ( t_fornecedor_cd_fornecedor )
        REFERENCES t_fornecedor ( cd_fornecedor );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
